#!/usr/bin/env node
// Generates docs/SOURCES.md (human-readable source log) from content/sources.json.
//   node tools/audit/sources_md.mjs        (npm run sources)
// content/sources.json itself is built by tools/audit/build_sources.mjs from the rulings, the Q&A bank and verify results.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const sources = JSON.parse(fs.readFileSync(path.join(ROOT, 'content/sources.json'), 'utf8'));
const TYPES = [
  ['quran', 'Quran — القرآن الكريم'],
  ['hadith', 'Hadith — الحديث النبوي'],
  ['madhhab', 'Madhhab references — مراجع المذاهب الأربعة'],
  ['contemporary', 'Contemporary fiqh bodies & fatwas — المجامع والهيئات المعاصرة'],
  ['other', 'Supporting references (approved-package sites) — مراجع مساندة'],
];
const STATUS = { machine_verified: '✅ machine_verified', pending_human: '⏳ pending_human', reviewed: '🎓 reviewed' };
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const out = [];
out.push('# Source log — سجل المصادر', '');
out.push('> Generated by `node tools/audit/sources_md.mjs` from [`content/sources.json`](../content/sources.json). Do not edit by hand.');
out.push('> يُولَّد آلياً من `content/sources.json`؛ لا تعدّله يدوياً.', '');

out.push('## How to verify — كيف تتحقق بنفسك', '');
out.push('1. **Run the audit:** `npm run audit` (= `node tools/audit/verify.mjs && node tools/audit/links.mjs`). It needs network access the first time (downloads are cached in `tools/audit/.cache/`; add `--no-cache` to re-fetch). Exit code 0 means every check passed.');
out.push('2. **Qur\'an** — every ayah is re-fetched from the King Fahd Glorious Qur\'an Printing Complex via [quranenc.com](https://quranenc.com) (`/api/v1/translation/aya/english_saheeh/{sura}/{aya}`). The Arabic must equal the Madinah-Mushaf text **exactly**; the English must equal the Complex-reviewed Saheeh International translation (footnote markers removed); every letter is also cross-checked against Tanzil. Click any Qur\'an link below to read the ayah on quranenc.com.');
out.push('3. **Hadith** — only hadith graded صحيح or حسن by an approved source are shown to players. Six-book texts are matched letter-by-letter (with harakat) against the sunnah.com text (hadith-api). For every hadith outside al-Bukhari/Muslim the record names the dorar.net entry (المحدث | المصدر | الرقم | خلاصة حكم المحدث) and links to it — open the dorar link to see the grade exactly as dorar shows it; where a HadeethEnc.com entry exists its grade is re-fetched by the audit. dorar.net and sunnah.com block automated clients, so those links are checked structurally and must be opened by a human.');
out.push('4. **Madhhab / contemporary** — open the link or the cited volume/page. These are **not** machine-verifiable and stay `pending_human` unless the auditor read the page directly.');
out.push('5. **What the status means:** `machine_verified` = the text (and, for hadith, the grade record) was matched against the source by `verify.mjs` or read directly by the auditor; `pending_human` = not matched, a person must check it; `reviewed` = a human scholar signed off (**none yet**). It does **not** mean a scholar reviewed the ruling.', '');
out.push('«موثّق آلياً» يعني أن النص طوبق آلياً (أو يدوياً) مع مصدره حرفاً بحرف، ولا يعني أن عالماً راجع الحكم؛ لم تُراجَع الأحكام بعدُ من عالم بشري. شغّل `npm run audit` لإعادة التحقق، وافتح أي رابط أدناه للاطلاع على المصدر.', '');

out.push('## Summary', '');
out.push('| Type | Entries | Verified | Not verified (needs a human) |', '|---|---|---|---|');
for (const [type, title] of TYPES) {
  const list = sources.filter((s) => s.type === type);
  out.push(`| ${title} | ${list.length} | ${list.filter((s) => s.verified).length} | ${list.filter((s) => !s.verified).length} |`);
}
out.push(`| **Total** | **${sources.length}** | **${sources.filter((s) => s.verified).length}** | **${sources.filter((s) => !s.verified).length}** |`, '');
for (const [type, title] of TYPES) {
  const list = sources.filter((s) => s.type === type);
  if (!list.length) continue;
  out.push(`## ${title}`, '');
  const hadith = type === 'hadith';
  out.push(`| # | Citation | Location | ${hadith ? 'Grade (grader) | ' : ''}Link | Status | Used in | How it was checked |`,
    `|---|---|---|${hadith ? '---|' : ''}---|---|---|---|`);
  list.forEach((s, i) => {
    const links = [[s.url, 'link'], [s.dorar_url, 'dorar'], [s.hadeethenc_url, 'HadeethEnc'], [s.sunnah_url && String(s.sunnah_url).split(/\s*;\s*/)[0], 'sunnah.com']]
      .filter(([u], k, a) => u && a.findIndex(([x]) => x === u) === k).map(([u, l]) => `[${l}](${u})`).join(' · ') || '—';
    out.push(`| ${i + 1} | ${esc(s.citation)} | ${esc(s.location)} | ${hadith ? `${esc(s.grade)} (${esc(s.grader)}) | ` : ''}${links} | ${STATUS[s.review_status] || esc(s.review_status)} | ${esc((s.used_in || []).join(', '))} | ${esc(s.verified_how)} |`);
  });
  out.push('');
}
fs.writeFileSync(path.join(ROOT, 'docs/SOURCES.md'), out.join('\n'));
console.log(`docs/SOURCES.md written (${sources.length} entries)`);
